routes:
  /:
    data: page.home
    template: home
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade

collections:
  /letters/:
    permalink: /letters/{slug}/
    template: index

taxonomies: